# Generated by Django 6.0.8 on 2026-10-02 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial_webhooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Event log entry',
                'verbose_name_plural': 'Event log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company_id', '-created_at'], name='actions_eventlog_company_idx'), models.Index(fields=['company_id', 'user_id', '-created_at'], name='actions_eventlog_user_idx')],
            },
        ),
    ]
