#!/usr/bin/env python3
"""Render nginx site config from the same env vars Django uses.

Filesystem: ``MEDIA_ROOT`` → ``alias`` for ``X-Accel-Redirect: /protected/…``.
S3: ``AWS_*`` → internal proxy for ``X-Accel-Redirect: /protected-s3/…``.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config.s3utils import infer_addressing_style, infer_s3_region, normalize_s3_endpoint


def _env(name: str, default: str = '') -> str:
    return os.getenv(name, default).strip()


def media_root() -> str:
    raw = _env('MEDIA_ROOT', '/app/data/media') or '/app/data/media'
    return raw.rstrip('/')


def nginx_resolver() -> str:
    return _env('NGINX_RESOLVER', '127.0.0.11 8.8.8.8') or '127.0.0.11 8.8.8.8'


def s3_proxy_parts() -> tuple[str, str, str] | None:
    """Return (origin, host_header, rewrite_prefix) or None if not using S3."""
    if _env('STORAGE_BACKEND', 'filesystem').lower() != 's3':
        return None
    bucket = _env('AWS_STORAGE_BUCKET_NAME')
    if not bucket:
        return None
    endpoint = normalize_s3_endpoint(_env('AWS_S3_ENDPOINT_URL'), bucket)
    region = infer_s3_region(endpoint, _env('AWS_S3_REGION_NAME', 'us-east-1'))
    style = infer_addressing_style(endpoint, _env('AWS_S3_ADDRESSING_STYLE'))

    if endpoint:
        origin = endpoint
        host = endpoint.split('://', 1)[-1]
        rewrite = f'/{bucket}/' if style != 'virtual' else '/'
        return origin, host, rewrite

    if style == 'path':
        origin = f'https://s3.{region}.amazonaws.com'
        host = f's3.{region}.amazonaws.com'
        return origin, host, f'/{bucket}/'

    origin = f'https://{bucket}.s3.{region}.amazonaws.com'
    host = f'{bucket}.s3.{region}.amazonaws.com'
    return origin, host, '/'


def _nginx_escape(value: str) -> str:
    return value.replace('\\', '\\\\').replace('"', '\\"')


def render() -> str:
    root = _nginx_escape(media_root())
    resolver = _nginx_escape(nginx_resolver())
    s3 = s3_proxy_parts()

    s3_location = ''
    if s3:
        origin, host, rewrite = (_nginx_escape(p) for p in s3)
        s3_location = f"""
    # S3 / MinIO / R2 — same AWS_* env as Django. Django signs the GET;
    # nginx fetches from this origin with X-Accel-Redirect: /protected-s3/<key>?<sig>
    location /protected-s3/ {{
        internal;
        resolver {resolver} valid=10s ipv6=off;
        resolver_timeout 5s;
        set $s3_backend "{origin}";
        rewrite ^/protected-s3/(.*)$ {rewrite}$1 break;
        proxy_pass $s3_backend;
        proxy_set_header Host {host};
        proxy_ssl_server_name on;
        proxy_set_header Authorization "";
        proxy_set_header Cookie "";
        proxy_hide_header x-amz-id-2;
        proxy_hide_header x-amz-request-id;
    }}
"""

    return f"""# Generated by tools/nginx/render-conf.py — do not edit on the running container.
server {{
    listen 8000 default_server;
    listen [::]:8000 default_server;
    server_name _;

    client_max_body_size 0;
    client_body_timeout 300s;

    proxy_http_version 1.1;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    location /protected/ {{
        internal;
        alias {root}/objects/;
    }}
{s3_location}
    location / {{
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Destination $http_destination;
        proxy_set_header Overwrite $http_overwrite;
        proxy_set_header Depth $http_depth;
    }}
}}
"""


def main(argv: list[str]) -> int:
    text = render()
    if len(argv) > 1:
        path = Path(argv[1])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8')
    else:
        sys.stdout.write(text)
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
