# Generated by Django 6.0.3 on 2026-08-08 17:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(unique=True)),
                ('max_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('used_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_bytes_per_user', models.BigIntegerField(blank=True, help_text='Optional default per-user quota for this company. Null/0 disables.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'company quota',
                'verbose_name_plural': 'company quotas',
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=100)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('public', models.BooleanField(default=False)),
                ('file_size_limit', models.BigIntegerField(blank=True, help_text='Optional max object size in bytes for this bucket.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('allowed_mime_types', models.JSONField(blank=True, default=list, help_text='Empty list = allow all. Otherwise list of MIME types / prefixes (e.g. image/*).')),
                ('owner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company_id', 'name'], name='storage_buc_company_4764d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('company_id', 'name'), name='storage_bucket_company_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('max_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('used_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user quota',
                'verbose_name_plural': 'user quotas',
                'constraints': [models.UniqueConstraint(fields=('company_id', 'user_id'), name='storage_userquota_company_user_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('size', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('etag', models.CharField(blank=True, default='', max_length=64)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('storage_key', models.CharField(max_length=2048)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.bucket')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['bucket', 'name'], name='storage_sto_bucket__17b8e6_idx'), models.Index(fields=['company_id', 'owner_id'], name='storage_sto_company_10a51a_idx'), models.Index(fields=['bucket', 'name', 'updated_at'], name='storage_sto_bucket__2b3578_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'name'), name='storage_object_bucket_name_uniq')],
            },
        ),
    ]
