# Generated by Django 6.0.3 on 2026-08-09 08:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('company', 'Company')], max_length=16)),
                ('subject_id', models.CharField(help_text='User id, group id, or company id depending on subject_type.', max_length=64)),
                ('resource_type', models.CharField(choices=[('bucket', 'Bucket'), ('folder', 'Folder prefix'), ('object', 'Object')], max_length=16)),
                ('resource_id', models.CharField(help_text='Bucket name, folder prefix, or object path / UUID.', max_length=1024)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], max_length=16)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny (block)')], default='allow', max_length=8)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'storage access grant',
                'verbose_name_plural': 'storage access grants',
            },
        ),
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['kind', 'name']},
        ),
        migrations.AddField(
            model_name='bucket',
            name='connector_provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bucket',
            name='kind',
            field=models.CharField(choices=[('company', 'Company private'), ('user', 'User private'), ('connector', 'External connector')], db_index=True, default='company', max_length=32),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='public',
            field=models.BooleanField(default=False, help_text='v1: always false. Public buckets are disabled.'),
        ),
        migrations.AddIndex(
            model_name='bucket',
            index=models.Index(fields=['company_id', 'kind'], name='storage_buc_company_25e417_idx'),
        ),
        migrations.AddIndex(
            model_name='bucket',
            index=models.Index(fields=['company_id', 'owner_id'], name='storage_buc_company_406129_idx'),
        ),
        migrations.AddIndex(
            model_name='storageaccessgrant',
            index=models.Index(fields=['company_id', 'resource_type', 'resource_id'], name='storage_sto_company_d79254_idx'),
        ),
        migrations.AddIndex(
            model_name='storageaccessgrant',
            index=models.Index(fields=['company_id', 'subject_type', 'subject_id'], name='storage_sto_company_e1914b_idx'),
        ),
    ]
