# Generated by Django 6.0.3 on 2026-08-09 15:29

import apps.storage.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_bucket_kinds_and_access_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaccessgrant',
            name='bucket_name',
            field=models.SlugField(blank=True, default='', help_text='Bucket this grant applies to. Empty means company bucket for folder/object grants.', max_length=100),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='kind',
            field=models.CharField(choices=[('company', 'Company'), ('user', 'User private (legacy)'), ('connector', 'External connector')], db_index=True, default='company', max_length=32),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='public',
            field=models.BooleanField(default=False, help_text='Always false. Anonymous access uses capability share links, not public buckets.'),
        ),
        migrations.CreateModel(
            name='ObjectShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=apps.storage.models._default_share_token, max_length=64, unique=True)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('created_by_id', models.PositiveIntegerField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional absolute expiry. Required if max_downloads is unset.', null=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, help_text='Optional download cap. Required if expires_at is unset.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='storage.storageobject')),
            ],
            options={
                'verbose_name': 'object share link',
                'verbose_name_plural': 'object share links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'object'], name='storage_obj_company_51730a_idx'), models.Index(fields=['created_by_id', 'created_at'], name='storage_obj_created_cfdd61_idx')],
            },
        ),
    ]
