# Generated by Django 6.0.3 on 2026-08-17 06:50

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


FOLDER_PLACEHOLDER = '.emptyFolderPlaceholder'


def _placeholder_name(folder_path: str) -> str:
    folder = (folder_path or '').strip().strip('/')
    if not folder:
        return FOLDER_PLACEHOLDER
    return f'{folder}/{FOLDER_PLACEHOLDER}'


def _storage_key(company_id, bucket_name, object_name, object_id) -> str:
    basename = (object_name or '').rsplit('/', 1)[-1] or 'blob'
    return f'shellui/{company_id}/{bucket_name}/{object_id}/{basename}'


def forwards_grant_fks(apps, schema_editor):
    Grant = apps.get_model('storage', 'StorageAccessGrant')
    Bucket = apps.get_model('storage', 'Bucket')
    StorageObject = apps.get_model('storage', 'StorageObject')

    for grant in Grant.objects.all():
        bucket_name = (grant.bucket_name or '').strip()
        if grant.resource_type == 'bucket':
            bucket_name = bucket_name or (grant.resource_id or '').strip()
        if not bucket_name:
            bucket_name = 'company'
        bucket = Bucket.objects.filter(company_id=grant.company_id, name=bucket_name).first()
        if bucket is None:
            grant.delete()
            continue
        grant.bucket = bucket
        rid = (grant.resource_id or '').strip().strip('/')

        if grant.resource_type == 'bucket':
            grant.object = None
            grant.save(update_fields=['bucket', 'object'])
            continue

        obj = None
        if grant.resource_type == 'object':
            try:
                uid = uuid.UUID(rid)
            except (ValueError, TypeError):
                uid = None
            if uid is not None:
                obj = StorageObject.objects.filter(bucket=bucket, id=uid).first()
            if obj is None and rid:
                obj = StorageObject.objects.filter(bucket=bucket, name=rid).first()
            if obj is None:
                grant.delete()
                continue
        elif grant.resource_type == 'folder':
            name = _placeholder_name(rid)
            obj = StorageObject.objects.filter(bucket=bucket, name=name).first()
            if obj is None:
                object_id = uuid.uuid4()
                obj = StorageObject.objects.create(
                    id=object_id,
                    bucket=bucket,
                    name=name,
                    company_id=bucket.company_id,
                    size=0,
                    storage_key=_storage_key(bucket.company_id, bucket.name, name, object_id),
                    mime_type='application/octet-stream',
                )
        else:
            grant.delete()
            continue

        grant.object = obj
        grant.save(update_fields=['bucket', 'object'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_user_bucket_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaccessgrant',
            name='bucket',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='access_grants',
                to='storage.bucket',
            ),
        ),
        migrations.AddField(
            model_name='storageaccessgrant',
            name='object',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='access_grants',
                to='storage.storageobject',
            ),
        ),
        migrations.RunPython(forwards_grant_fks, noop_reverse),
        migrations.AlterField(
            model_name='storageaccessgrant',
            name='bucket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='access_grants',
                to='storage.bucket',
            ),
        ),
        migrations.RemoveIndex(
            model_name='storageaccessgrant',
            name='storage_sto_company_d79254_idx',
        ),
        migrations.RemoveField(
            model_name='storageaccessgrant',
            name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='storageaccessgrant',
            name='resource_id',
        ),
        migrations.AddIndex(
            model_name='storageaccessgrant',
            index=models.Index(fields=['company_id', 'resource_type'], name='storage_sto_company_1169ae_idx'),
        ),
        migrations.AddIndex(
            model_name='storageaccessgrant',
            index=models.Index(fields=['bucket', 'resource_type'], name='storage_sto_bucket__814848_idx'),
        ),
        migrations.AddConstraint(
            model_name='storageaccessgrant',
            constraint=models.CheckConstraint(
                condition=(
                    Q(resource_type='bucket', object__isnull=True)
                    | Q(resource_type__in=['folder', 'object'], object__isnull=False)
                ),
                name='storage_grant_object_matches_type',
            ),
        ),
    ]
